import http.cookiejar
import json
import os
import urllib.request
from datetime import datetime, timezone
base = "https://www.kaggle.com"
api = base + "/api/i/competitions.CompetitionService/ListCompetitions"
dataDir = os.environ.get("DATA_DIR", "data")
pageSize = int(os.environ.get("PAGE_SIZE", "20"))
listOpt = os.environ.get("LIST_OPTION", "LIST_OPTION_DEFAULT")
ua = "Mozilla/5.0 (X11; Linux x86_64) kaggle-competitions-watch/1.0"
catKeys = ("id", "name", "displayName", "slug", "fullPath")
metaKeys = ("firstSeen", "lastChanged")
def fetch():
    jar = http.cookiejar.CookieJar()
    op = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))
    op.addheaders = [("user-agent", ua), ("accept", "application/json")]
    op.open(base + "/competitions", timeout=30).read()
    tok = next(c.value for c in jar if c.name == "XSRF-TOKEN")
    sel = {"competitionIds": [], "listOption": listOpt, "sortOption": "SORT_OPTION_NEWEST", "hostSegmentIdFilter": 0, "searchQuery": "", "prestigeFilter": "PRESTIGE_FILTER_UNSPECIFIED", "visibilityFilter": "VISIBILITY_FILTER_UNSPECIFIED", "participationFilter": "PARTICIPATION_FILTER_UNSPECIFIED", "tagIds": [], "excludeTagIds": [], "requireSimulations": False, "requireKernels": False, "requireHackathons": False}
    body = {"selector": sel, "pageToken": "", "pageSize": pageSize, "readMask": "competitions,totalResults"}
    hdr = {"content-type": "application/json", "x-xsrf-token": tok, "origin": base, "referer": base + "/competitions"}
    req = urllib.request.Request(api, data=json.dumps(body).encode(), headers=hdr)
    with op.open(req, timeout=30) as r:
        return json.load(r)
def clean(c):
    c = dict(c)
    c["url"] = base + "/competitions/" + c["competitionName"]
    c["categories"] = [{k: x[k] for k in catKeys if k in x} for x in c.get("categories", [])]
    return c
def rewardText(r):
    r = r or {}
    if r.get("id") == "USD" and r.get("quantity") is not None:
        return "${:,}".format(r["quantity"])
    return r.get("id") or "-"
def load(p):
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)
def dump(p, obj):
    with open(p, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=1)
        f.write("\n")
def ts(v):
    return (v or "-")[:16].replace("T", " ")
def md(comps, total, now):
    rows = ["# Kaggle competitions (newest first)", "", "Updated %s UTC. totalResults %s. Generated by watch.py, do not edit. Start = dateEnabled (when the competition went live)." % (now, total), "", "| # | Competition | Host | Reward | Start (UTC) | Deadline (UTC) | Teams |", "|---|---|---|---|---|---|---|"]
    for i, c in enumerate(comps, 1):
        title = c["title"].replace("|", "\\|")
        rows.append("| %d | [%s](%s) | %s | %s | %s | %s | %s |" % (i, title, c["url"], c.get("hostName", "-"), rewardText(c.get("reward")), ts(c.get("dateEnabled")), ts(c.get("deadline")), c.get("totalTeams", "-")))
    return "\n".join(rows) + "\n"
def stripTs(txt):
    return "\n".join(l for l in txt.splitlines() if not l.startswith("Updated "))
def main():
    resp = fetch()
    comps = [clean(c) for c in resp.get("competitions", [])]
    total = resp.get("totalResults")
    if not comps:
        raise SystemExit("empty competitions list, refusing to write")
    os.makedirs(dataDir, exist_ok=True)
    latestPath = os.path.join(dataDir, "latest.json")
    storePath = os.path.join(dataDir, "competitions.json")
    mdPath = "COMPETITIONS.md"
    oldLatest = load(latestPath) or {}
    oldStore = load(storePath) or {}
    store = dict(oldStore)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    added, changed = [], []
    for c in comps:
        k = str(c["id"])
        old = oldStore.get(k)
        rec = dict(c)
        if old is None:
            added.append(c["competitionName"])
            rec["firstSeen"] = rec["lastChanged"] = now
        else:
            rec["firstSeen"] = old.get("firstSeen", now)
            same = {kk: v for kk, v in old.items() if kk not in metaKeys} == c
            rec["lastChanged"] = old.get("lastChanged", now) if same else now
            if not same:
                changed.append(c["competitionName"])
        store[k] = rec
    store = dict(sorted(store.items(), key=lambda kv: kv[1].get("dateEnabled", ""), reverse=True))
    newLatest = {"listOption": listOpt, "pageSize": pageSize, "totalResults": total, "competitions": comps}
    mdNew = md(comps, total, now)
    mdOld = open(mdPath, encoding="utf-8").read() if os.path.exists(mdPath) else ""
    if {k: v for k, v in oldLatest.items() if k != "updatedAt"} == newLatest and oldStore == store and stripTs(mdOld) == stripTs(mdNew):
        print("no change (%d competitions on page, %s total)" % (len(comps), total))
        return
    dump(latestPath, {"updatedAt": now, **newLatest})
    dump(storePath, store)
    with open(mdPath, "w", encoding="utf-8") as f:
        f.write(mdNew)
    print("updated %s: page %d, store %d, total %s, added %s, changed %s" % (now, len(comps), len(store), total, added, changed))
if __name__ == "__main__":
    main()
